# -*- coding: utf-8 -*-
"""Algorithmic Trading using Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14OZL2eRyrgLVOgz2tNfQrRay-RldDEZ1
"""

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import yfinance as yf

stock = yf.Ticker('AAPL')
data = stock.history(period='1y')
data.head()

data['momentum'] = data['Close'].pct_change()

figure = make_subplots(rows=2, cols=1)
figure.add_trace(go.Scatter(x=data.index, y=data['Close'], name='Close'))
figure.add_trace(go.Scatter(x=data.index, y=data['momentum'], name='Momentum',yaxis='y2'))
figure.add_trace(go.Scatter(x=data.loc[data['momentum'] > 0].index,
                         y=data.loc[data['momentum'] > 0]['Close'],
                         mode='markers', name='Buy',
                         marker=dict(color='green', symbol='triangle-up')))
figure.add_trace(go.Scatter(x=data.loc[data['momentum'] < 0].index,
                         y=data.loc[data['momentum'] < 0]['Close'],
                         mode='markers', name='Sell',
                         marker=dict(color='red', symbol='triangle-down')))
figure.update_layout(title='Algorithmic Trading using Momentum Strategy',
                  xaxis_title='Date',
                  yaxis_title='Price')
figure.update_yaxes(title_text='Momentum', secondary_y=True)
figure.show()

